import { Inter } from "next/font/google";
import styles from "../page.module.css";
import Header from "@/components/header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <main className={styles.main}>
            <h3>Blog Layout</h3>
            <Link href="/blog/one" style={{color:"#00f"}}>Blog 1</Link>
            <Link href="/blog/two" style={{color:"#00f"}}>Blog 2</Link>
            <Link href="/blog/customer" style={{color:"#00f"}}>Customer Details</Link>
            {children}
        </main>
  );
}
